 CREATE DATABASE college_administration_select_operations;
 CREATE TABLE `college_administration_select_operations`.`select_operations` 
 (
 `student_roll_no` INT NOT NULL,
  `Student_department_code` INT NOT NULL,
  `Student_Names` VARCHAR(45) NOT NULL,
  `Student_location` VARCHAR(45) NOT NULL,
  `Student_first graduate` VARCHAR(45) NOT NULL,
  `Student_degree` VARCHAR(45) NOT NULL,
  `Student_Year` INT NOT NULL,
  `Student_Gender` VARCHAR(45) NOT NULL,
  `Student_Email_id` VARCHAR(45) NOT NULL,
  `non_Teaching_Faculty_Department` INT NOT NULL,
  `non_Teaching_Faculty_Department_codee` INT NOT NULL,
  `Non-Teaching_Faculty_Names` VARCHAR(45) NOT NULL,
  `Non-Teaching_Faculty_mail_id` VARCHAR(45) NOT NULL,
  `Non-Teaching_Faculty_contact_no` VARCHAR(45) NOT NULL,
  `Department_code` INT NOT NULL,
  `Department_names` VARCHAR(45) NOT NULL,
  `Student_Father_Name` VARCHAR(45) NOT NULL,
  `Student_Mother_Name` VARCHAR(45) NOT NULL,
  `Student_Parents_Occupation` VARCHAR(45) NOT NULL,
  `Student_Parents_Annual_Income` VARCHAR(45) NULL,
  `Head_of_the_Department` INT NOT NULL,
  `HOD_Mail_id` VARCHAR(45) NOT NULL,
  `Hod_Contact_no` VARCHAR(45) NOT NULL,
  `HOD_Intercom` VARCHAR(45) NOT NULL,
  `HOD_qualification` VARCHAR(45) NOT NULL,
  `HOD_experience` VARCHAR(45) NOT NULL,
  `Teaching_faculty_id` INT NOT NULL,
  `Teaching_Faculty_Department_name` INT NOT NULL,
  `Teaching_Faculty_Names` VARCHAR(45) NOT NULL,
  `Teaching_Faculty_mail id` VARCHAR(45) NOT NULL,
  `Teaching_Faculty_Qualification` VARCHAR(45) NOT NULL,
  `Teaching_Faculty_contact_no` VARCHAR(45) NOT NULL,
  `Teaching_Faculty_Area_of_Expertise` VARCHAR(45) NOT NULL,
  `taching_faculty` INT NOT NULL,
  `non_teaching_faculty` INT NOT NULL
 );